<?php
/**
* @file
* Install, update and uninstall functions for the system module.
*/


/**
 * Delete update_notify email variable. Not all pages should send mails with update notif. this would spam some mailboxes.
 */
function ggp_update_7101(&$sandbox) {
  variable_del('update_notify_emails');



/**
 * Update Theme Settings. Enable social
 */
function ggp_update_7102(&$sandbox) {
  variable_del('update_notify_emails');
}